services:
  api:
    environment:
      SONAR_CHAT_BASE_URL: ${SONAR_CHAT_BASE_URL}
      SONAR_CHAT_MODEL: ${SONAR_CHAT_MODEL}
      SONAR_CHAT_API_KEY: ${SONAR_CHAT_API_KEY:-not-needed}
      SONAR_EMBEDDING_PROVIDER: ${SONAR_EMBEDDING_PROVIDER:-openai}
      SONAR_EMBEDDING_BASE_URL: ${SONAR_EMBEDDING_BASE_URL}
      SONAR_EMBEDDING_MODEL: ${SONAR_EMBEDDING_MODEL}
      SONAR_EMBEDDING_API_KEY: ${SONAR_EMBEDDING_API_KEY:-not-needed}
